# Generated by Django 5.2.3 on 2025-06-25 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_users_alter_authenticationlogs_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticationlogs",
            name="roaster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roasters",
            ),
        ),
        migrations.AddField(
            model_name="authenticationlogs",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beanvarietals",
            name="farm",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.farms"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuppingattributescores",
            name="evaluation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.cuppingevaluations",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuppingevaluations",
            name="evaluation_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
        ),
        migrations.AddField(
            model_name="cuppingevaluations",
            name="evaluator_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuppingevaluations",
            name="roast_batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastbatches",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverymanifestitems",
            name="manifest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.deliverymanifests",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverymanifestitems",
            name="packaged_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.packagedproducts",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliverymanifests",
            name="delivery_rider_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryreceipts",
            name="po",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.purchaseorders",
            ),
        ),
        migrations.AddField(
            model_name="deliveryreceipts",
            name="transaction_by_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryreceipts",
            name="transaction_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finalproducts",
            name="blend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.blends",
            ),
        ),
        migrations.AddField(
            model_name="finalproducts",
            name="packaging_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.packagingmaterials",
            ),
        ),
        migrations.AddField(
            model_name="finalproducts",
            name="roast_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastprofiles",
            ),
        ),
        migrations.AddField(
            model_name="greenbeanlots",
            name="bean_varietal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.beanvarietals",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="greenbeanlots",
            name="custom_attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="greenbeanlots",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.purchaseorders",
            ),
        ),
        migrations.AddField(
            model_name="greenbeanprocessinglog",
            name="green_bean_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.greenbeanlots",
            ),
        ),
        migrations.AddField(
            model_name="greenbeanprocessinglog",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.joborders",
            ),
        ),
        migrations.AddField(
            model_name="greenbeanprocessinglog",
            name="operator_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="greenbeanprocessinglog",
            name="roast_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastbatches",
            ),
        ),
        migrations.AddField(
            model_name="greenbeanprocessinglog",
            name="storage_zone",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.storagezones",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joborders",
            name="requested_by_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machinehealthlogs",
            name="roaster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roasters",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mobileunitlocationhistory",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagedproducts",
            name="dr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.deliveryreceipts",
            ),
        ),
        migrations.AddField(
            model_name="packagedproducts",
            name="final_product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.finalproducts",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagedproducts",
            name="packaged_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="packagedproducts",
            name="packaging_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
        ),
        migrations.AddField(
            model_name="packagedproducts",
            name="roast_batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastbatches",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="bean_varietal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.beanvarietals",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="consumable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.consumables",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="custom_attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="item_type",
            field=models.CharField(default="Consumable", max_length=20),
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="po",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.purchaseorders",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorders",
            name="ordered_by_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="green_bean_lot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.greenbeanlots",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.joborders",
            ),
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="operator_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="roast_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="roast_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastprofiles",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roastbatches",
            name="roaster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roasters",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roastedcoffeebins",
            name="current_storage_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.storagezones",
            ),
        ),
        migrations.AddField(
            model_name="roastedcoffeebins",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.joborders",
            ),
        ),
        migrations.AddField(
            model_name="roastedcoffeebins",
            name="packaging_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.packagingmaterials",
            ),
        ),
        migrations.AddField(
            model_name="roastedcoffeebins",
            name="roast_batch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastbatches",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roasters",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
        ),
        migrations.AddField(
            model_name="roastertelemetrylogs",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roastbatches",
            ),
        ),
        migrations.AddField(
            model_name="roastertelemetrylogs",
            name="roaster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.roasters",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storagezones",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.locations",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="authenticationlogs",
            name="auth_method",
            field=models.CharField(
                choices=[
                    ("Password", "Password"),
                    ("QR Code", "QR Code"),
                    ("Biometric", "Biometric"),
                    ("System", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="authenticationlogs",
            name="status",
            field=models.CharField(
                choices=[("Success", "Success"), ("Failure", "Failure")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="deliverymanifestitems",
            name="status",
            field=models.CharField(
                choices=[
                    ("Loaded", "Loaded"),
                    ("Delivered", "Delivered"),
                    ("Returned", "Returned"),
                    ("Damaged", "Damaged"),
                ],
                default="Loaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliverymanifests",
            name="delivery_partner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliverymanifests",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("Internal", "Internal Fleet"),
                    ("Third Party", "Third-Party Courier"),
                    ("Pickup", "Customer Pickup"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deliverymanifests",
            name="manifest_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="deliverymanifests",
            name="status",
            field=models.CharField(
                choices=[
                    ("Dispatched", "Dispatched"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Delayed", "Delayed"),
                ],
                default="Dispatched",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="greenbeanlots",
            name="lot_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="greenbeanlots",
            name="quality_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Specialty", "Specialty Grade"),
                    ("Premium", "Premium Grade"),
                    ("Commercial", "Commercial Grade"),
                    ("Off-Grade", "Off-Grade"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="greenbeanlots",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="greenbeanprocessinglog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Drying Cherries", "Drying Cherries"),
                    ("Drying GCB", "Drying GCB"),
                    ("Dehulling", "Dehulling"),
                    ("Depulping", "Depulping"),
                    ("Storaged", "Sealed and Stored"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joborders",
            name="job_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="joborders",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Roasting", "Roasting"),
                    ("Blending", "Blending"),
                    ("Packaging", "Packaging"),
                    ("Grinding", "Grinding"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="joborders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("On Hold", "On Hold"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locations",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="locations",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="locations",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="locations",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="locations",
            name="type",
            field=models.CharField(
                choices=[
                    ("Hub", "Hub"),
                    ("Spoke", "Spoke"),
                    ("Roastery", "Roastery"),
                    ("Warehouse", "Warehouse"),
                    ("Mobile Unit", "Mobile Unit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="locations",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="machinehealthlogs",
            name="status_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="machinehealthlogs",
            name="subsystem_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="machinehealthlogs",
            name="test_result",
            field=models.CharField(
                choices=[
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                    ("Warning", "Warning"),
                    ("Skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitems",
            name="quantity_received",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Credit Card", "Credit Card"),
                    ("Net Terms", "Net Terms"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="po_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="supplier_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="roastedcoffeebins",
            name="bin_qr_code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="roastedcoffeebins",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Available", "Available"),
                    ("Allocated", "Allocated to Job"),
                    ("Empty", "Empty"),
                ],
                default="Available",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authenticationlogs",
            unique_together={("auth_log_id", "timestamp")},
        ),
        migrations.AlterUniqueTogether(
            name="deliverymanifestitems",
            unique_together={("manifest", "packaged_item")},
        ),
        migrations.AlterUniqueTogether(
            name="machinehealthlogs",
            unique_together={("health_log_id", "timestamp")},
        ),
        migrations.AlterUniqueTogether(
            name="mobileunitlocationhistory",
            unique_together={("location_history_id", "timestamp")},
        ),
        migrations.AlterUniqueTogether(
            name="roastertelemetrylogs",
            unique_together={("log_id", "timestamp")},
        ),
    ]
