# Generated by Django 5.2.3 on 2025-06-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_authenticationlogs_roaster_authenticationlogs_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MqttDevice",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        help_text="A unique identifier for the device, e.g., 'platform_scale_100kg'",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="The full MQTT topic this device publishes to.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("SCALE", "Platform Scale (Additive)"),
                            ("DOSER", "Subtractive Doser"),
                            ("TELEMETRY", "Roaster Telemetry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
