# Generated by Django 5.2.3 on 2025-06-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_mqttdevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beanvarietals",
            options={"verbose_name_plural": "Bean varietals"},
        ),
        migrations.AlterField(
            model_name="beanvarietals",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
