# Generated by Django 5.2.3 on 2025-06-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_beanvarietals_options_alter_beanvarietals_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farms",
            options={"verbose_name_plural": "Farms"},
        ),
        migrations.AlterField(
            model_name="farms",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="farms",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="farms",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
