# Generated by Django 5.2.3 on 2025-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_farms_options_alter_farms_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authenticationlogs",
            options={"verbose_name_plural": "Authentication logs"},
        ),
        migrations.AlterModelOptions(
            name="blends",
            options={"verbose_name_plural": "Blends"},
        ),
        migrations.AlterModelOptions(
            name="consumables",
            options={"verbose_name_plural": "Consumables"},
        ),
        migrations.AlterModelOptions(
            name="cuppingattributescores",
            options={"verbose_name_plural": "Cupping attribute scores"},
        ),
        migrations.AlterModelOptions(
            name="cuppingevaluations",
            options={"verbose_name_plural": "Cupping evaluations"},
        ),
        migrations.AlterModelOptions(
            name="customers",
            options={"verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="deliverymanifestitems",
            options={"verbose_name_plural": "Delivery manifest items"},
        ),
        migrations.AlterModelOptions(
            name="deliverymanifests",
            options={"verbose_name_plural": "Delivery manifests"},
        ),
        migrations.AlterModelOptions(
            name="deliveryreceipts",
            options={"verbose_name_plural": "Delivery receipts"},
        ),
        migrations.AlterModelOptions(
            name="finalproducts",
            options={"verbose_name_plural": "Final products"},
        ),
        migrations.AlterModelOptions(
            name="greenbeanlots",
            options={"verbose_name_plural": "Green bean lots"},
        ),
        migrations.AlterModelOptions(
            name="greenbeanprocessinglog",
            options={"verbose_name_plural": "Green bean processing logs"},
        ),
        migrations.AlterModelOptions(
            name="joborders",
            options={"verbose_name_plural": "Job orders"},
        ),
        migrations.AlterModelOptions(
            name="locations",
            options={"verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="machinehealthlogs",
            options={"verbose_name_plural": "Machine health logs"},
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={"verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="mobileunitlocationhistory",
            options={"verbose_name_plural": "Mobile unit location history"},
        ),
        migrations.AlterModelOptions(
            name="mqttdevice",
            options={"verbose_name_plural": "MQTT devices"},
        ),
        migrations.AlterModelOptions(
            name="packagedproducts",
            options={"verbose_name_plural": "Packaged products"},
        ),
        migrations.AlterModelOptions(
            name="packagingmaterials",
            options={"verbose_name_plural": "Packaging materials"},
        ),
        migrations.AlterModelOptions(
            name="purchaseorderitems",
            options={"verbose_name_plural": "Purchase order items"},
        ),
        migrations.AlterModelOptions(
            name="purchaseorders",
            options={"verbose_name_plural": "Purchase orders"},
        ),
        migrations.AlterModelOptions(
            name="roastbatches",
            options={"verbose_name_plural": "Roast batches"},
        ),
        migrations.AlterModelOptions(
            name="roastedcoffeebins",
            options={"verbose_name_plural": "Roasted coffee bins"},
        ),
        migrations.AlterModelOptions(
            name="roasters",
            options={"verbose_name_plural": "Roasters"},
        ),
        migrations.AlterModelOptions(
            name="roastertelemetrylogs",
            options={"verbose_name_plural": "Roaster telemetry logs"},
        ),
        migrations.AlterModelOptions(
            name="roastprofiles",
            options={"verbose_name_plural": "Roast profiles"},
        ),
        migrations.AlterModelOptions(
            name="storagezones",
            options={"verbose_name_plural": "Storage zones"},
        ),
        migrations.AlterField(
            model_name="blends",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="consumables",
            name="unit_of_measure",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cuppingattributescores",
            name="attribute_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customers",
            name="branding_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customers",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customers",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryreceipts",
            name="dr_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="finalproducts",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="greenbeanprocessinglog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Drying Cherries", "Drying Cherries"),
                    ("Drying GCB", "Drying GCB"),
                    ("Dehulling", "Dehulling"),
                    ("Depulping", "Depulping"),
                    ("Storaged", "Sealed and Stored"),
                    ("Roast Usage", "Used in Roast Batch"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="topic",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="packagedproducts",
            name="packaged_item_qr_code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="packagingmaterials",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cash", "Cash"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Credit Card", "Credit Card"),
                    ("Net Terms", "Net Terms"),
                    ("GCash", "GCash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roastbatches",
            name="batch_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="roasters",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="roasters",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="roastertelemetrylogs",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="roastprofiles",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="storagezones",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="storagezones",
            name="zone_identifier",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="storagezones",
            name="zone_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
