"""
Django settings for basilioroaster_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-a+2buc4=b9ahkgt*7sca&q4um9qc$zf00$90-k_e&$62p=+xyk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# In backend/basilioroaster_project/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My Apps
    'core',  # This line was changed from 'app'
    'users',
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "basilioroaster_project.urls"

# In basilioroaster_project/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        
        # [RECOMMENDATION] This line tells Django to look in 'backend/core/templates'
        # It now uses the correct pathlib syntax.
        'DIRS': [BASE_DIR / 'core' / 'templates'], 
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "basilioroaster_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'roaster_data_db',      #
        'USER': 'postgres',              #
        'PASSWORD': '1234',              #
        'HOST': 'localhost',             #
        'PORT': '5432',                  #
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Add this to the bottom of basilioroaster_project/settings.py

# [RECOMMENDATION] Update this to point to the new dashboard page.
LOGIN_REDIRECT_URL = '/app/dashboard/'

# This setting is correct. After logout, the user goes to the homepage, which then redirects to login.
LOGOUT_REDIRECT_URL = '/'

# This setting is correct. It tells Django's @login_required decorator where to find the login page.
LOGIN_URL = '/users/login/'
# At the bottom of settings.py

# --- MQTT and HiveMQ Configuration ---
MQTT_SETTINGS = {
    'BROKER_HOST': "ebdca87f8eb340cf96898aaee1fc1dae.s1.eu.hivemq.cloud",
    'BROKER_PORT': 8883,
    'TOPIC_ROOT': "inventory/#", # Subscribe to all inventory topics
    'USERNAME': "Basilio",
    'PASSWORD': "AirRoaster2011!",
    'CLIENT_ID': "django_inventory_subscriber"
}